loomx.loom_version="1.16-SNAPSHOT"


mod.id = "woolboots"
mod.name = "Wool Boots"
mod.group = "notenlish"
mod.version = "0.1.0"
mod.channel_tag = ""
mod.description = "Stealthily move with wool boots"
mod.authors = ["Notenlish"]
mod.contributors = []
mod.inception_year = "2026"
mod.license.name = "MIT"
mod.license.url = "https://opensource.org/licenses/MIT"
mod.license.dist = "repo"
mod.sources_url = "https://github.com/Notenlish/wool-boots"
mod.homepage_url = "https://github.com/Notenlish/wool-boots"
mod.issues_url = "https://github.com/Notenlish/wool-boots/issues"
mod.discord_url = ""
mod.environment = "both"
[[mod.pom.developers]]
id = "notenlish"
name = "Notenlish"
url = "https://github.com/ghost"

[fabric]
deps.fabric-loader = "0.19.2"

[fabric."1.21.1"]
deps.minecraft = "1.21.1"
deps.fabric-api = "0.116.7+1.21.1"
deps.modmenu = "11.0.4"

[fabric."1.21.7"]
deps.minecraft = "1.21.7"
deps.fabric-api = "0.128.1+1.21.7"
deps.modmenu = "15.0.0"
publish.additionalVersions = ["1.21.6"]

[fabric."26.1.2"]
deps.minecraft = "26.1.2"
deps.fabric-api = "0.146.1+26.1.2"
deps.modmenu = "18.0.0-alpha.8"
publish.additionalVersions = ["26.1.1", "26.1"]

[fabric."26.2"]
deps.minecraft = "26.2"
deps.fabric-api = "0.157.0+26.2"
deps.modmenu = "20.0.1"
publish.additionalVersions = []
# not sure if 26.2 has additional versions

[forge]

[forge."1.19.2"]
deps.minecraft = "1.19.2"
deps.forge = "43.5.2"

[neoforge]

[neoforge."1.21.1"]
deps.minecraft = "1.21.1"
deps.neoforge = "21.1.213"

[neoforge."1.21.7"]
deps.minecraft = "1.21.7"
deps.neoforge = "21.7.1-beta"
publish.additionalVersions = ["1.21.6"]

[neoforge."26.1.2"]
deps.minecraft = "26.1.2"
deps.neoforge = "26.1.2.29-beta"
publish.additionalVersions = ["26.1.1", "26.1"]

[neoforge."26.2"]
deps.minecraft = "26.2"
deps.neoforge = "26.2.0.59"
publish.additionalVersions = []
